"""Custom Hatch build hook for era5-etl.

Two jobs:
  1. Mirror the contents of ``VERSION`` into ``src/era5_etl/__version__.py``
     so ``from era5_etl.__version__ import __version__`` always reflects the
     authoritative version.
  2. Build the React/Vite SPA into ``src/era5_etl/web/static/`` so the wheel
     ships with a usable web UI. Set ``ERA5_ETL_SKIP_UI_BUILD=1`` to skip
     this step (CI environments without Node/Bun).

The hook is plugged in via ``pyproject.toml``::

    [tool.hatch.build.hooks.custom]
    path = "hatch_build.py"
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

REPO_ROOT = Path(__file__).resolve().parent
VERSION_FILE = REPO_ROOT / "VERSION"
WEB_UI_DIR = REPO_ROOT / "web-ui"
STATIC_DIR = REPO_ROOT / "src" / "era5_etl" / "web" / "static"
VERSION_MODULE = REPO_ROOT / "src" / "era5_etl" / "__version__.py"


class BuildUIHook(BuildHookInterface):
    PLUGIN_NAME = "custom"

    def initialize(self, version: str, build_data: dict) -> None:  # noqa: D401
        self._sync_version()
        if os.environ.get("ERA5_ETL_SKIP_UI_BUILD") == "1":
            self._log("ERA5_ETL_SKIP_UI_BUILD=1 set; skipping SPA build")
            return
        self._build_spa()

    # ---- version -----------------------------------------------------------

    def _sync_version(self) -> None:
        if not VERSION_FILE.exists():
            self._log(f"VERSION file missing at {VERSION_FILE}; skipping version sync")
            return
        ver = VERSION_FILE.read_text(encoding="utf-8").strip()
        VERSION_MODULE.parent.mkdir(parents=True, exist_ok=True)
        VERSION_MODULE.write_text(
            f'"""Generated by hatch_build.py from VERSION."""\n\n__version__ = "{ver}"\n',
            encoding="utf-8",
        )
        self._log(f"Synced __version__ = {ver!r}")

    # ---- SPA ---------------------------------------------------------------

    def _build_spa(self) -> None:
        if not WEB_UI_DIR.exists():
            self._log(f"web-ui directory not found at {WEB_UI_DIR}; skipping SPA build")
            return

        runner = self._pick_runner()
        if runner is None:
            self._log(
                "Neither bun nor pnpm/npm found on PATH; "
                "skipping SPA build (set ERA5_ETL_SKIP_UI_BUILD=1 to silence)"
            )
            return

        install_cmd, build_cmd = runner
        self._log(f"Building SPA with: {' '.join(install_cmd)} && {' '.join(build_cmd)}")
        subprocess.run(install_cmd, cwd=str(WEB_UI_DIR), check=True)
        subprocess.run(build_cmd, cwd=str(WEB_UI_DIR), check=True)

        if not (STATIC_DIR / "index.html").exists():
            raise RuntimeError(
                f"SPA build did not produce {STATIC_DIR / 'index.html'}; "
                "check the web-ui/ build pipeline."
            )
        self._log(f"SPA bundle ready at {STATIC_DIR}")

    def _pick_runner(self) -> tuple[list[str], list[str]] | None:
        if shutil.which("bun"):
            return (["bun", "install"], ["bun", "run", "build"])
        if shutil.which("pnpm"):
            return (["pnpm", "install"], ["pnpm", "run", "build"])
        if shutil.which("npm"):
            return (["npm", "install"], ["npm", "run", "build"])
        return None

    def _log(self, message: str) -> None:
        print(f"[hatch_build] {message}", file=sys.stderr)
